Repository many-protocol/specification, pull requests merged in 2022-10, with the labels that each got.

#69 Add events info filtering for multisig state
  attributes/network/9_account_features/cddl/1_account_multisig.cddl
  attributes/network/cddl/4_events.cddl
Labels: documentation

#76 Fix CI by adding an order to the evaluation of rules
  .github/workflows/cddl.yml
  Makefile
  scripts/make_cddl.bash
Labels: bug

#72 Fix async status response
  attributes/network/cddl/8_async.cddl
Labels: bug

#75 Add endpoints info data and information about CQRS
  attributes/network/0_base.adoc
  attributes/network/cddl/0_base.cddl
  spec/protocol/endpoints.adoc
Labels: enhancement
