Repository many-protocol/specification, pull requests merged in 2022-09, with the labels that each got.

#56 Initial commit of the Data attribute which exposes various data about the server and its neighborhood
  attributes/network/5_data.adoc
  attributes/network/5_data/0_accounts_count.adoc
  attributes/network/6_ledger_commands.adoc
  attributes/network/7_kvstore_commands.adoc
  attributes/network/cddl/5_data.cddl
  spec/cddl/many.cddl
  spec/cddl/types.cddl
Labels: documentation

#62 Rework kvstore spec
  attributes/network/3_kvstore.adoc
  attributes/network/7_kvstore_commands.adoc
  attributes/network/9_account_features/2_account_kvstore.adoc
  attributes/network/9_account_features/cddl/2_account_kvstore.cddl
  attributes/network/cddl/3_kvstore.cddl
  attributes/network/cddl/7_kvstore_commands.cddl
Labels: documentation, enhancement

#64 block-query -> single-block-query
  attributes/network/cddl/1_blockchain.cddl
Labels: bug, documentation
